Solutions/TemplateProject.Web.Mvc/Areas/Admin/Controllers/CategoriesController.cs
using System.Web.Mvc;
using SharpArch.NHibernate.Web.Mvc;
using TemplateProject.Domain;
using TemplateProject.Domain.Contracts.Tasks;
using MvcContrib;

namespace TemplateProject.Web.Mvc.Areas.Admin.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryTasks _tasks;

        public CategoriesController(ICategoryTasks tasks)
        {
            _tasks = tasks;
        }

        public ActionResult Index()
        {
            var categories = _tasks.GetAll();
            return View(categories);
        }

        public ActionResult Details(int id)
        {
            var category = _tasks.Get(id);
            return View(category);
        }

        public ActionResult Create()
        {
            return View(new Category());
        } 

        public ActionResult Edit(int id)
        {
            var category = _tasks.Get(id);
            return View(category);
        }

        [Transaction]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Edit(Category category)
        {
            if (ModelState.IsValid && category.IsValid())
            {
                _tasks.CreateOrUpdate(category);
                return this.RedirectToAction(x => x.Index());
            }

            if (category.Id == 0)
                return View("Create", category);
            return View(category);
        }

        [Transaction]
        public ActionResult Delete(int id)
        {
            _tasks.Delete(id);
            return this.RedirectToAction(x => x.Index());
        }
    }
}

Solutions/TemplateProject.Web.Mvc/Areas/Admin/Views/Categories/Create.cshtml
@model Category

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Edit", "Categories"))
{
    <text>
    @Html.AntiForgeryToken()
    @Html.LabelFor(x => x.Name)
    <div>@Html.TextBoxFor(x => x.Name) @Html.ValidationMessageFor(x => x.Name)</div>
    <input type="submit" value = "Create Category" />
    </text>
}

Solutions/TemplateProject.Web.Mvc/Areas/Admin/Views/Categories/Details.cshtml
@model Category

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<ul>
<li>ID: @Model.Id</li>
<li>Created: @Model.Created)</li>
<li>Modified: @Model.Modified)</li>
<li>Name: @Model.Name</li>
<li>Products: @if(Model.Products.Count == 0){ <text>N/A</text> }
              @foreach (var product in Model.Products.Select((x, i) => new { Data = x, Index = i}))
              {
                  @(product.Index < Model.Products.Count - 1 ? product.Data.Name+", " : product.Data.Name)
              }</li>
</ul>
@(Html.ActionLink<CategoriesController>(x => x.Edit(Model.Id), "Edit"))

Solutions/TemplateProject.Web.Mvc/Areas/Admin/Views/Categories/Edit.cshtml
@model Category

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Categories"))
{
    <text>
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.Id)
    @Html.LabelFor(x => x.Name)
    <div>@Html.TextBoxFor(x => x.Name) @Html.ValidationMessageFor(x => x.Name)</div>
    <input type="submit" value = "Save Category" />
    </text>
}
@(Html.ActionLink<CategoriesController>(x => x.Delete(Model.Id), "Delete This Category"))

Solutions/TemplateProject.Web.Mvc/Areas/Admin/Views/Categories/Index.cshtml
@using MvcContrib.UI.Grid
@model IList<Category>

@{
    ViewBag.Title = "Categories";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Categories</h2>

@Html.Grid(Model).Columns(column =>
{
    column.For(c => c.Id).Named("ID");
    column.For(c => c.Name);
    column.For(c => c.Created).Named("Created");
    column.For(c => c.Modified).Named("Modified");
    column.For(c => c.Products.Count == 0 ? "N/A" : 
        String.Join(", ", c.Products.Select(p => Html.ActionLink<ProductsController>(x => x.Edit(p.Id), p.Name)))).Named("Products").Encode(false);
    column.For(c => Html.ActionLink<CategoriesController>(x => x.Edit(c.Id), "edit")).Named(string.Empty);
}).Empty("No Categories")

@(Html.ActionLink<CategoriesController>(x => x.Create(), "Create New Category"))