Solutions/TemplateProject.Web.Mvc/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using Microsoft.Web.Helpers;
using SharpArch.Domain.Commands;
using SharpArch.NHibernate.Web.Mvc;
using TemplateProject.Domain;
using TemplateProject.Domain.Contracts.Tasks;
using MvcContrib;
using TemplateProject.Infrastructure.Queries;
using TemplateProject.Tasks.Commands;
using TemplateProject.Tasks.CustomContracts;
using TemplateProject.Web.Mvc.Areas.Admin.Models;

namespace TemplateProject.Web.Mvc.Areas.Admin.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductTasks _productTasks;
        private readonly ICategoryTasks _categoryTasks;
        private readonly IProductsQuery _productsQuery;
        private readonly ICommandProcessor _commandProcessor;
        private readonly ICaptchaTasks _captchaTasks;

        private const int DefaultPageSize = 10;

        public ProductsController(IProductTasks productTasks, ICategoryTasks categoryTasks, IProductsQuery productsQuery, 
            ICommandProcessor commandProcessor, ICaptchaTasks captchaTasks)
        {
            _productTasks = productTasks;
            _categoryTasks = categoryTasks;
            _productsQuery = productsQuery;
            _commandProcessor = commandProcessor;
            _captchaTasks = captchaTasks;
        }

        public ActionResult Index(int? page)
        {
            var categories = _categoryTasks.GetAll();
            ViewBag.Categories = categories.ToDictionary(k => k.Id, v => v.Name);
            var products = _productsQuery.GetPagedList(page ?? 1, DefaultPageSize);
            return View(products);
        }

        public ActionResult Create()
        {
            var categories = _categoryTasks.GetAll();
            if (categories.Count == 0)
                ViewBag.CategoryError = "You must create at least one Category before creating a Product.";

            var model = new ProductEditViewModel
            {
                Categories = _categoryTasks.GetAll(),
                Product = new Product(),
                SelectedCategoryId = 0
            };
            return View(model);
        } 

        public ActionResult Edit(int id)
        {
            var product = _productTasks.Get(id);
            var model = new ProductEditViewModel
            {
                Categories = _categoryTasks.GetAll(),
                Product = product,
                SelectedCategoryId = product.Category.Id
            };
            return View(model);
        }

        [Transaction]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (_captchaTasks.Validate(ConfigurationManager.AppSettings["ReCaptchaPrivate"]))
            {
                if (ModelState.IsValid && product.IsValid())
                {
                    _productTasks.CreateOrUpdate(product);
                    return this.RedirectToAction(x => x.Index(null));
                }
            }
            else
                ModelState.AddModelError("ReCaptcha", "ReCaptcha failed!");

            var model = new ProductEditViewModel
            {
                Categories = _categoryTasks.GetAll(),
                Product = product,
                SelectedCategoryId = product.Category.Id
            };

            if (product.Id == 0)
                return View("Create", model);
            return View(model);
        }

        [Transaction]
        public ActionResult Delete(int id)
        {
            _productTasks.Delete(id);
            return this.RedirectToAction(x => x.Index(null));
        }

        //Ajax action
        [Transaction]
        [HttpPost]
        public ActionResult ChangeCategory(FormCollection collection)
        {
            var catId = Int32.Parse(collection["category"]);
            var productIds = new List<int>();
            foreach (var key in collection.AllKeys)
            {
                int productId;
                if(Int32.TryParse(key, out productId) && collection[key] != bool.FalseString.ToLowerInvariant())
                    productIds.Add(productId);
            }

            var command = new MassCategoryChangeCommand(catId, productIds);
            var results = _commandProcessor.Process(command);
            if (results.Success)
                return new ContentResult { Content = "Categories successfully changed! Refresh to see the changes.", ContentType = "text/html" };
            return new ContentResult { Content = "One or more categories failed to change!", ContentType = "text/html" };
        }
    }
}

Solutions/TemplateProject.Web.Mvc/Areas/Admin/Views/Products/Create.cshtml
@using Microsoft.Web.Helpers
@using TemplateProject.Web.Mvc.Areas.Admin.Models
@using TemplateProject.Web.Mvc.Extensions
@model ProductEditViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h3>@ViewBag.CategoryError</h3>

@using (Html.BeginForm("Edit", "Products"))
{
    <text>
    @Html.AntiForgeryToken()
    @Html.LabelFor(x => x.Product.Name)
    <div>@Html.TextBoxFor(x => x.Product.Name) @Html.ValidationMessageFor(x => x.Product.Name)</div>

    @Html.LabelFor(x => x.Product.DefaultAvailability)
    <div>@Availability.Online.ToString() @Html.RadioButtonFor(x => x.Product.DefaultAvailability, Availability.Online)
    @Availability.Store.ToString() @Html.RadioButtonFor(x => x.Product.DefaultAvailability, Availability.Store)
    @Availability.ThirdParty.ToString() @Html.RadioButtonFor(x => x.Product.DefaultAvailability, Availability.ThirdParty)  @Html.ValidationMessageFor(x => x.Product.DefaultAvailability)</div>

    @Html.LabelFor(x => x.Product.MultipleAvailability)
    <div>@FlaggedAvailability.Online.ToString() @Html.CheckBoxWithValue("MultipleAvailabilities", FlaggedAvailability.Online)
    @FlaggedAvailability.Store.ToString() @Html.CheckBoxWithValue("MultipleAvailabilities", FlaggedAvailability.Store)
    @FlaggedAvailability.ThirdParty.ToString() @Html.CheckBoxWithValue("MultipleAvailabilities", FlaggedAvailability.ThirdParty)
    @Html.HiddenFor(x => x.Product.MultipleAvailability)
    </div>

    @Html.LabelFor(x => x.Product.Category)
    <div>@Html.DropDownListFor(m => m.SelectedCategoryId, new SelectList(Model.Categories, "Id", "Name"), "Select a Category")  @Html.ValidationMessageFor(x => x.SelectedCategoryId)</div>

    <div>@ReCaptcha.GetHtml(publicKey: "6LcX-8cSAAAAAODY6NtodM9R9oa3uTo8lbutdVIY") @Html.ValidationMessage("ReCaptcha")</div>

    <input type="submit" value = "Create Product" />
    </text>
}

<script type="text/javascript">
    $(document).ready(function () {
        $('form').one('submit', function (e) {
            e.preventDefault();
            var multiChecked = $("[name='MultipleAvailabilities']:checked").map(function () { return this.value; }).get().join(',');
            $('#Product_MultipleAvailability').val(multiChecked);
            $(this).submit();
        });
    });
</script>

Solutions/TemplateProject.Web.Mvc/Areas/Admin/Views/Products/Edit.cshtml
@using TemplateProject.Web.Mvc.Areas.Admin.Models
@using TemplateProject.Web.Mvc.Extensions
@model ProductEditViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Products"))
{
    <text>
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.Product.Id)
    @Html.LabelFor(x => x.Product.Name)
    <div>@Html.TextBoxFor(x => x.Product.Name) @Html.ValidationMessageFor(x => x.Product.Name)</div>

    @Html.LabelFor(x => x.Product.DefaultAvailability)
    <div>@Availability.Online.ToString() @Html.RadioButtonFor(x => x.Product.DefaultAvailability, Availability.Online)
    @Availability.Store.ToString() @Html.RadioButtonFor(x => x.Product.DefaultAvailability, Availability.Store)
    @Availability.ThirdParty.ToString() @Html.RadioButtonFor(x => x.Product.DefaultAvailability, Availability.ThirdParty)  @Html.ValidationMessageFor(x => x.Product.DefaultAvailability)</div>

    @Html.LabelFor(x => x.Product.MultipleAvailability)
    <div>@Html.CheckBoxesForFlagsEnum(x => x.Product.MultipleAvailability, Model.Product.MultipleAvailability)</div>

    @Html.LabelFor(x => x.Product.Category)
    <div>@Html.DropDownListFor(m => m.SelectedCategoryId, new SelectList(Model.Categories, "Id", "Name"))  </div>
    <input type="submit" value = "Save Product" />
    </text>
}
@(Html.ActionLink<ProductsController>(x => x.Delete(Model.Product.Id), "Delete This Product"))


Solutions/TemplateProject.Web.Mvc/Areas/Admin/Views/Products/Index.cshtml
@using MvcContrib.Pagination
@using MvcContrib.UI.Grid
@model IPagination<Product>

@{
    ViewBag.Title = "Products";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Products</h2>

@(Html.ActionLink<ProductsController>(x => x.Create(), "Create New Product"))

<div id="products">
@using (Html.BeginForm("ChangeCategory", "Products"))
{
    <text>
    @Html.Grid(Model).Columns(column =>
    {
        column.For(p => p.Id).Named("ID");
        column.For(p => p.Name);
        column.For(p => p.Created).Named("Created");
        column.For(p => p.Modified).Named("Modified");
        column.For(p => Html.ActionLink<CategoriesController>(x => x.Details(p.Category.Id), p.Category.Name)).Named("Category");
        column.For(p => Html.ActionLink<ProductsController>(x => x.Edit(p.Id), "edit")).Named(string.Empty);
        column.For(p => Html.CheckBox(p.Id.ToString(), false));
    }).Empty("No Products")

 @if (Model.TotalItems > 0)
 {
     @Html.Label("category", "Category")
     <div>@Html.DropDownList("category", new SelectList(ViewBag.Categories, "Key", "Value"))
         <input type="submit" value = "Change Category for Selected Products" /></div>
     <div id="change-category-success"></div>
 }
    </text>
}
</div>
<div>
@if (Model.HasPreviousPage)
{
    <text>@(Html.ActionLink<ProductsController>(c => c.Index(Model.PageNumber - 1), "Previous"))</text>
}

@if (Model.HasNextPage)
{
    <text>@(Html.ActionLink<ProductsController>(c => c.Index(Model.PageNumber + 1), "Next"))</text>
}
</div>

<div>
Page @Model.PageNumber of @Model.TotalPages
</div>

<script type="text/javascript">
$(document).ready(function () {
  $('#products form').live('submit', function () {
    $.post($(this).attr('action'), $(this).serialize(), function (data) {
      $("#change-category-success").html(data);
    });
    return false;
  });
});
</script>